~int~ is a datatype, ~struct~ defines a datatype, ~class~ defines a datatype.
Why the hell do 'untyped' languages have classes? 
Well, the thruth is, those languages are not actually untyped.

An untyped language would not have /classes/. 


* Getting Started
  :PROPERTIES:
  :CUSTOM_ID: getting-started
  :END:

Starting to write /programs/ raises a few questions: what /language/ to
use? what /paradigm/ to focus on? what is a reliable setup to get
started?

If you want to try /programming/ for the first time, you might not want
to put a lot of effort and time into setting up a /development
environment/, which might take hours to days to set up, depending on
your experience. In this case the easiest way to get started is a modern
/browser/ with it's integrated programming language =JavaScript=.

** Programming the Browser

*** Introduction

   :PROPERTIES:
   :CUSTOM_ID: programming-the-browser
   :END:

The /programming language/ of each modern browser is =JavaScript=. And
you should use the latest version of your browser in any case, because
old browser versions are a serious security risk. All browsers do have a
/console/ for =JavaScript=.

#+BEGIN_QUOTE
  This text will not describe how to open the console; the method to
  open it may vary for each browser and even for each version. It is
  also easy to find online. As general statement, this text will not
  describe all steps to solve a task. The focus lays on referencing well
  written guidelines and tutorials, providing information hard to find
  elsewhere and being a glue to create a holistic picture of the topic.
  The autor trusts in the intelligence of the reader to solve any
  problem by itself; and in improving by doing so.
#+END_QUOTE

When you have managed to open the console, there will be an input
/prompt/, which will allow you to type something in. There might also
some other output in the console present, probably in red od yellow
colors. The reason for that is, the console relates to the currently
open tab and shows information about it. In rare cases it might even
interact with the code you will try to type in. To get a completely
clean console, you will have to open an empty tab; to do so, open a new
tab and type into the /address bar/:

#+BEGIN_SRC
     about:blank
#+END_SRC

It is important to type every /character/ in this /string/ correctly,
this includes /blank spaces/: there are no blank spaces in this string,
and none can be added. This is a general rule in programming, a single
error, wich includes any misspelling like mixing up 0 with O or =.= with
=,= or putting a space at the wrong spot will break the entire program.
Even the few freedoms the definition of the programming language allows,
are taken away by /style guides/, which will define the place of every
single symbol, that is going to be typed in the program. For this reason
it is a good advice to start very slowly, making sure every character
and every symbol is on the right spot, and being eager to prevent as
much errors as possible from the very beginning. It is an difficult
task, to write error free programs as soon as they get to a interesting
complexity. There are multiple levels to master in programming: the most
basic one is the getting the /syntax/ and /semantics/
[[https://en.wikibooks.org/wiki/Introduction_to_Programming_Languages/Grammars]]

#+BEGIN_QUOTE
  We see a lot of feature-driven product design in which the cost of
  features is not properly accounted. Features can have a negative value
  to consumers because they make the products more difficult to
  understand and use. We are finding that people like products that just
  work. It turns out that design that just work are much harder to
  produce than designs that assemble long lists of features.
#+END_QUOTE

But at the current point of time, we do not have to think about features
too much, because the core features of the language will lead us to
examples automatically: A first example of programming are basic
calculations, type the following /commands/ into the console and hit the
enter key afterwards.

#+BEGIN_SRC javascript
     2 + 3;
#+END_SRC

The result will be shown in the next line. In this case leaving away the
blank spaces before and after the =+= symbol will lead to the same
result. But the style guide forces us to put them there; and therefore
it would be a bad idea to leave them away. The language does not force
the =;= symbol to be at the end of the the line, but leaving it away can
lead to obscure errors in =JavaScript=, therefore it is key to end every
/expression/ in =JavaScript= with the =;= symbol [[Is it correct to say
it in that way?]]. There are expressions which use multiple lines but
most of them live on a single line, so not every line will end with a
semicolon but most of them will. It is nice to have a console at hand,
which can do basic calculations, even parentheses do work:

#+BEGIN_SRC javascript
     2 * (-5 + 2) / 2;
#+END_SRC

Typing a predefined example and making it work is a first satisfying
step. But pretty soon it will be forgotten again. A good way to get a
more profound experience, is to take the gained knowledge and try out
new combinations. Driving it to a point, where the attempts break the
system, and figuring out possible reasons for the breakage, is even
better. If you did do the former already -- even before reading this
lines---the probability for you to become a programmer is high. If you
did the latter, your chances are good to become a good programmer.

*** First JS Steps

#+BEGIN_SRC javascript
2 + 3

2 + (5/7 - 3)
#+END_SRC

Programming examples are often utilizing mathematical examples; this has two reasons: First, programming is historically rootet in mathematics.  Second, programming and mathematics share a certain aspect of their nature: they are abstract.  This means, the concepts of programming, as well as the concepts of mathematics are basically just existing in our minds.  This again, has multiple consequences, e.g. xxx.  But the more imporant consequence is, that this concepts are clear [pure?].

Now we know that programming languages allow us to calculate mathematical expressions.  And we also know now, where the name /computer/ is coming from.

In the next step we introduce variables.  Variables allow us to structure a program into separate steps and increase the expressiveness of the program.

#+BEGIN_SRC javascript
a = 2
b = 3
c = a + b
#+END_SRC

By choosing speaking variable names, we can increase the expressiveness of the program: reading the programm tells us, what it is actually doing.

*** Variables
    
#+BEGIN_SRC javascript
apples = 2
pears = 3
number_of_goods = apples + pears
average = number_of_goods / 2
#+END_SRC

Usually there are restrictions to variable names, e.g. they have to start with a letter or they have to be a singular string of letters, which is also the reason why we wrote ~number_of_goods~ with ~_~ (underscores) instead of spaces to sparate the words.

*** Functions

Another way to structure a program is not only to give certain values a name but also to name a sequence of instrucitons of instructions.


#+BEGIN_SRC javascript
arithmetic_average = function(first_value, second_value) {
    sum = first_value + second_value
    average = sum / 2
    return average
}
#+END_SRC

In JavaScript this is called a function.  The advantage of functions is not only increasing the expressiveness of a program, it also allows the reuse of a part of a program.  The function ~average()~ can now be used on multiple occurances.  We can now calculate the average of different food types.

#+BEGIN_SRC javascript
salad = 5
tomatos = 6

average_fruits = arithmetic_average(apples, pears)
average_vegetables = arithmetic_average(salad, tomatos)
#+END_SRC

*** Data Strucutres

Now these functions are a bit impractical, because they use exactly two parameters.
In a more realisic scenario of course we would like to calculate the average of a arbitrary number of goods.
One way to solve this problem is to first define a data structure that holds a series of values.
In JavaScript we can use the curly braces ~{}~ to define a data structure that allows to define a series of values with names.

#+BEGIN_SRC javascript
fruits = {
    apples: 2
    pears: 3
    cherries: 4
}

vegetables = {
    salad: 5
    tomatos: 6
}
#+END_SRC

The name on the left side of the colon is called /key/ and the part on the right side of the colon is called /value/.
We can access these keys now with the following notation (note the ~'~ (quotes) around the key):

#+BEGIN_SRC javascript
fruits['apples']
fruits['cherries']
#+END_SRC

*** Iteration

Some data structures allow to iterate over them.
The ~for...in~ construct goes through every key of our data structure.

#+BEGIN_SRC javascript
arithmetic_average = function(goods) {
    sum = 0
    number = 0
    for(key in goods) {
        sum = sum + goods[key]
	number = number + 1
    }
    average = sum / number
    return average
}
#+END_SRC

By putting all information regarding a goods category into a data structure, we were able to pass this data structure to a function, independet of the number of goods stored in that data structure.
Inside the function we use a loop to iterate over all elements of the data strtructure.
A loop simply executes some code for each element.

*** Decisions

Another important concept of programming are decisions.
The ~if ... else~ construct allows to validate some code and if it is true, it executes one block of code, and if it is false (else), it executes another block of code.
We could define a function that calculates the absolute value of a number:
If it is larger or equal to 0 return the number unchanged, else, return the negative of the number:

#+BEGIN_SRC javascript
abs = function(number) {
    if (number >= 0) {
        absolute_value = number
    }
    else {
        absolute_value = -1 * number
    }
    return absolute_value
}
#+END_SRC

The function, that calculates the absolute value of a number, can also be written much shorter.
What advantages and disadvantages could those versions have?

#+BEGIN_SRC javascript
abs = function(number) {
    if (number < 0) {
        number = -1 * number
    }
    return number
}
#+END_SRC

*** Reuse

Using a

*** Mathematics and Programming
    
** Computer Hardware
   :PROPERTIES:
   :CUSTOM_ID: computer-hardware
   :END:

If you do not own a computer or are not very experienced with it, get
one and start to get used to it. Do not worry about playing around with
it. If there is no important data on it, nothing important can get lost
(and if you have important data on it, it should be double /backed up/
anyways). And as long as it does not get physically broken, there is
almost nothing you can do, which breaks the computer permanently. For
programming the system requirements are low, a second hand /laptop/ for
€ 200 to € 300 will be sufficient. Do not worry about the usual
characteristics like processor /clock rate/, number of /cores/, size of
/RAM/ or /drive/ space. Useful upgrades for programming are a good
/screen/ and a quality /keyboard/. Those two devices handle the majority
of your interaction with the computer. If you do serious work, you will
spend many hours daily looking at the screen and your fingers will push
the keys on your keyboard million of times.

*** Computer Screen
    :PROPERTIES:
    :CUSTOM_ID: computer-screen
    :END:

Therefore a clear and steady image is an important quality criteria for
a screen used for programming in contrast to color and reaction time,
which might be relevant for image editing and gaming, but not for
programming. A second important criteria for a programming screen is the
resulution. As a programmer you will have an /editor/ and at least one
window which shows the result of your program and /debugging/
information or an /IDE/, which combines all of the former tasks, open at
all time. On top of that beginners will have an browser window open. As
soon as you have learned how to use it, the /interweb/ will answer the
majority of your questions quickly. Expectably one question will lead to
another, therefore the browser will usually have many /tabs/ open at the
same time. This is not only true for beginners, but also for experienced
programmers. Modern programmers are required to update themselves on
upcomming technologies, new /frameworks/ and possibly emerging
/programming languages/ multiple times each year, which leads to a
constant learning process, and being the browser the best friend of a
programmer. As a result a lot of information will be presented
simultaneously, which multiple screens or such with high resolution
desireable.

*** Keyboard
    :PROPERTIES:
    :CUSTOM_ID: keyboard
    :END:

There is a variety of keyboards with different characteristics. Laptop
keyboards do have much shorter travel distance for a keystroke than
solid desktop keyboards. Therefore a good tactile feedback is most
important for laptop keyboards. Heavy typists might even want a keyboard
with mechanical switches. If you are familiar with touch typing you
might already have a preferred tactile feedback, and you should probably
stick to it. If you are not familiar with touch typing, it is advisable
to start with training right away; it will impove your productivity in
short time and allow you to focus on the task.

*** High Hardware Requirements
    :PROPERTIES:
    :CUSTOM_ID: high-hardware-requirements
    :END:

For specialised cases in programming, despite what was sayd above,
programming requires hardware components with high performance. But such
requirements are very specific for each field and the specific tasks in
such a field. In some cases a obscene amount of RAM might be absolutely
neccessary while the performance of other components is secondary, and
in other cases a program can run only on a /super computer/. While it
will hardly be understandable for a beginner, such requirements become
clear, when working on such a topic. Therefore the evaluation of special
hardware requirement is left for the reader.

** Computer Software
   :PROPERTIES:
   :CUSTOM_ID: computer-software
   :END:

>> install Gentoo


* Index

program
function
procedure
structure
data structure
block
code block
variable
readability
clarity
performance
object
oop
functional programming
structured programming
literate programming
procedual programming
imperative
declerative

paradigm
programming paradigm
principle
